"use client";

import { useCallback, useEffect, useState } from "react";
import { useWorkspace } from "@/context/WorkspaceContext";
import { api, ApiError } from "@/lib/api";
import { Card, CardHeading } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";
import type { DailySummary, Order, Paginated, Product } from "@/lib/types";

export default function OverviewPage() {
  const { current } = useWorkspace();
  const [summary, setSummary] = useState<DailySummary | null>(null);
  const [summaryLoading, setSummaryLoading] = useState(false);
  const [summaryError, setSummaryError] = useState<string | null>(null);
  const [orders, setOrders] = useState<Order[]>([]);
  const [lowStock, setLowStock] = useState<Product[]>([]);

  const loadStats = useCallback(async () => {
    if (!current) return;

    const [orderPage, productPage] = await Promise.all([
      api.get<Paginated<Order>>(
        `/api/v1/workspaces/${current.id}/orders?limit=100`,
      ),
      api.get<Paginated<Product>>(
        `/api/v1/workspaces/${current.id}/products?limit=100`,
      ),
    ]);

    setOrders(orderPage.items);
    setLowStock(
      productPage.items.filter(
        (p) =>
          p.inventory &&
          p.inventory.quantity - p.inventory.reserved <=
            p.inventory.lowStockThreshold,
      ),
    );
  }, [current]);

  useEffect(() => {
    loadStats();
  }, [loadStats]);

  async function generateSummary() {
    if (!current) return;
    setSummaryLoading(true);
    setSummaryError(null);

    try {
      const result = await api.post<DailySummary>(
        `/api/v1/workspaces/${current.id}/ai/daily-summary`,
        {},
      );
      setSummary(result);
    } catch (err) {
      setSummaryError(
        err instanceof ApiError ? err.message : "Couldn't generate the summary.",
      );
    } finally {
      setSummaryLoading(false);
    }
  }

  const pendingCount = orders.filter((o) => o.status === "PENDING").length;
  const activeCount = orders.filter((o) =>
    ["PAID", "PROCESSING", "FULFILLING", "SHIPPED"].includes(o.status),
  ).length;
  const deliveredCount = orders.filter((o) => o.status === "DELIVERED").length;

  return (
    <div className="flex flex-col gap-6">
      <div>
        <p className="font-mono text-xs uppercase tracking-widest2 text-graphite-500">
          {current?.name}
        </p>
        <h1 className="text-2xl font-semibold text-graphite-50">Overview</h1>
      </div>

      <div className="grid grid-cols-3 gap-4">
        <StatCard label="Awaiting payment" value={pendingCount} accent="amber" />
        <StatCard label="In progress" value={activeCount} accent="freight" />
        <StatCard label="Delivered" value={deliveredCount} accent="green" />
      </div>

      <Card>
        <div className="mb-4 flex items-center justify-between">
          <CardHeading className="mb-0">AI daily summary</CardHeading>
          <Button
            variant="secondary"
            onClick={generateSummary}
            disabled={summaryLoading}
          >
            {summaryLoading
              ? "Generating…"
              : summary
                ? "Regenerate"
                : "Generate"}
          </Button>
        </div>

        {summaryError && (
          <p className="text-sm text-signal-red">{summaryError}</p>
        )}

        {summary ? (
          <div>
            <p className="whitespace-pre-line text-sm leading-relaxed text-graphite-200">
              {summary.summary}
            </p>
            <p className="mt-3 font-mono text-xs text-graphite-500">
              {summary.generatedBy === "ai"
                ? "Generated by AI"
                : "Template fallback (no AI key configured)"}
            </p>
          </div>
        ) : (
          <p className="text-sm text-graphite-400">
            Pulls today's order activity into a short operational brief — what
            shipped, what's stuck, what needs attention.
          </p>
        )}
      </Card>

      <Card>
        <CardHeading>Low stock ({lowStock.length})</CardHeading>

        {lowStock.length === 0 ? (
          <p className="text-sm text-graphite-400">
            Nothing below its reorder threshold right now.
          </p>
        ) : (
          <ul className="flex flex-col gap-2">
            {lowStock.map((p) => (
              <li
                key={p.id}
                className="flex items-center justify-between font-mono text-sm"
              >
                <span className="text-graphite-200">{p.name}</span>
                <span className="text-amber-400">
                  {(p.inventory!.quantity - p.inventory!.reserved)
                    .toString()
                    .padStart(3, "0")}{" "}
                  available
                </span>
              </li>
            ))}
          </ul>
        )}
      </Card>
    </div>
  );
}

function StatCard({
  label,
  value,
  accent,
}: {
  label: string;
  value: number;
  accent: "amber" | "freight" | "green";
}) {
  const colors = {
    amber: "text-amber-400",
    freight: "text-freight-400",
    green: "text-signal-green",
  };

  return (
    <Card>
      <p className="text-xs uppercase tracking-widest2 text-graphite-400">
        {label}
      </p>
      <p
        className={`mt-2 font-mono text-3xl font-semibold tabular-nums ${colors[accent]}`}
      >
        {value}
      </p>
    </Card>
  );
}